### ISSUE TITLE
players found in frames that were not part of original set

### ISSUE THREAD

**Issue by IvanMalison** [CUBTeamRocket/boxcar-frames#1]
2023-04-11 21:20:58 ryzen-shine rocket_league_mmr_prediction.load[346772] WARNING Tensor load failure for 4bf8e2a6-56cc-4f6b-838d-0eb75a1dcb5d, Process ended with unexpected error Some("Players found in frames that were not part of original set. found: {}, original: {Xbox(2535455243337951), PlayStation(Ps4Id { online_id: 4946652041341234753, name: \"x_SaltyCracker_x\", unknown1: [98, 56, 117, 115, 112, 115, 52, 0, 1, 0, 0, 0, 0, 0, 0, 0] }), Epic(\"560007753d44426baca20e75e46b4943\"), PlayStation(Ps4Id { online_id: 6159481374091691009, name: \"STK_Shadowhakkay\", unknown1: [98, 55, 117, 115, 112, 115, 52, 0, 1, 0, 0, 0, 0, 0, 0, 0] })}")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/imalison/Projects/rocket-league-mmr-prediction/rocket_league_mmr_prediction/console.py", line 71, in load_game_dataset
    result = assesor.get_replay_statuses(load_tensor=False)
  File "/home/imalison/Projects/rocket-league-mmr-prediction/rocket_league_mmr_prediction/load.py", line 216, in get_replay_statuses
    return {
  File "/home/imalison/Projects/rocket-league-mmr-prediction/rocket_league_mmr_prediction/load.py", line 217, in <dictcomp>
    uuid: self._get_replay_status(uuid, load_tensor=load_tensor)
  File "/home/imalison/Projects/rocket-league-mmr-prediction/rocket_league_mmr_prediction/load.py", line 263, in _get_replay_status
    raise e
  File "/home/imalison/Projects/rocket-league-mmr-prediction/rocket_league_mmr_prediction/load.py", line 259, in _get_replay_status
    _, meta = self._replay_set.get_replay_tensor(uuid)
  File "/home/imalison/Projects/rocket-league-mmr-prediction/rocket_league_mmr_prediction/load.py", line 130, in get_replay_tensor
    uuid, *self._replay_set.get_replay_tensor(uuid)
  File "/home/imalison/Projects/rocket-league-mmr-prediction/rocket_league_mmr_prediction/load.py", line 171, in get_replay_tensor
    replay_meta, np_array = boxcars_py.get_replay_meta_and_numpy_ndarray(replay_path)
Exception: Process ended with unexpected error Some("Players found in frames that were not part of original set. found: {}, original: {Xbox(2535455243337951), PlayStation(Ps4Id { online_id: 4946652041341234753, name: \"x_SaltyCracker_x\", unknown1: [98, 56, 117, 115, 112, 115, 52, 0, 1, 0, 0, 0, 0, 0, 0, 0] }), Epic(\"560007753d44426baca20e75e46b4943\"), PlayStation(Ps4Id { online_id: 6159481374091691009, name: \"STK_Shadowhakkay\", unknown1: [98, 55, 117, 115, 112, 115, 52, 0, 1, 0, 0, 0, 0, 0, 0, 0] })}")
bash-5.2$

**Comment by davechurchill** [comment]
AFAIK this just happens in some replays. You can find actors in the network frames that are not present in PlayerStats. Not much you can do about it other than ignore PlayerStats and re-parse it all yourself from the frames
