### ISSUE TITLE
Car actor for player not found

### ISSUE THREAD

**Issue by IvanMalison** [CUBTeamRocket/boxcar-frames#5]
2023-06-04 17:42:42 rlrml INFO Downloding game from ball chasing /shared/rlbc_replays/temp/bb589e36-9b6d-4f29-89ac-582962edf8c9.replay
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/imalison/Projects/rlrml/rlrml/console.py", line 225, in wrapped
    return fn(builder)
           ^^^^^^^^^^^
  File "/home/imalison/Projects/rlrml/rlrml/console.py", line 655, in apply_model
    meta, ndarray = builder.load_game_from_filepath(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/imalison/Projects/rlrml/rlrml/console.py", line 403, in _load_game_from_filepath
    meta, tensor = boxcars_py.get_ndarray_with_info_from_replay_filepath(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Car actor for player Xbox(2535472783252083) not found.

**Comment by colonelpanic8** [comment]
Closing as fixed.

I pulled the original Ballchasing replay from the issue (`bb589e36-9b6d-4f29-89ac-582962edf8c9`) and checked it against the current processing path. The replay now processes successfully with the default Python-style ndarray feature set (`BallRigidBody`, `PlayerRigidBody`, `PlayerBoost`, `PlayerAnyJump`) instead of failing with `Car actor for player Xbox(...) not found`.

I also added the replay under `assets/replays/issue_5_car_actor_not_found.replay` plus a regression test that asserts the replay still produces ndarray output with all 4 players present, including both Xbox players.

Why this counts as fixed: the original failure mode was losing the player->car mapping for one of the Xbox players while building ndarray features. That no longer happens on current `master`, and the new regression replay/test now covers that exact replay so the issue should not silently come back.
